### PR TITLE
Upgrading Spring Boot to latest version

### LINKED ISSUE #181: Upgrade dependencies and Spring Boot version
Upgrade to latest Spring Boot project version

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #181 

Before submitting a pull request, please read
https://github.com/bancolombia/scaffold-clean-architecture/wiki/Contributing

## Category
- [ ] Feature
- [x] Fix

## Checklist
- [x] The pull request is complete according to the [guide of contributing](https://github.com/bancolombia/scaffold-clean-architecture/wiki/Contributing)
- [x] Automated tests are written
- [x] The documentation is up-to-date
- [x] The pull request has a descriptive title that describes what has changed, and provides enough context for the changelog

### CODE REVIEW

**Comment by jakspok** [comment]
Thanks for you contribution ...

**Review by jakspok — APPROVED** [review]
Thanks for you contribution ...

**Review by juancgalvis — CHANGES_REQUESTED** [review]
Please include additional upgrades, because other libraries should be upgraded.

undertow, jetty, please check that existing code will not have deprecations

**Comment by dericop** [comment]
@jakspok and @ElvertMora:
Please upgrade the dependencies that @juancgalvis recommend for approve this PR!

**Comment by mohitsaxenaknoldus** [comment]
I can do it if you let me know which packages you want upgraded.

**Comment by jakspok** [comment]
Hello, how are you, could you please upload the version of undertow to version 2.6 and in the same way the version of apache tomcat, also the version of spring-boot to version 2.6

**Comment by mohitsaxenaknoldus** [comment]
> @mohitsaxenaknoldus Hello, how are you, could you please upload the version of undertow to version 2.6, also the version of spring-boot to version 2.6

Where should I add it?

**Comment by ElvertMora** [comment]
thanks for  your contribution @mohitsaxenaknoldus ,  the spring project was update to 2.6 from  2.1.2 version

**Pull request closed without merging**
